name: Building crdroid

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
           
            
       - name: Sync recovery source and device tree
         run: |
              repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
              curl -o .repo/local_manifests/local_manifests.xml https://raw.githubusercontent.com/Arafattex/local_manifest/Lancelot_pixel/local_manifest.xml --create-dirs
              repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

             
       - name: Build
         run: |
              
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: crdroid.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/crdroid.zip
            retention-days: 5
