name: Dumpyara 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: remove pkg and setting repo
         run: |
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            pip3 install dumpyara
            pip3 install .
            pip3 install aospdtgen
            
       - name: Adding and Sync source
         run: |
              wget https://hugeota.d.miui.com/V13.0.5.0.SJCCNXM/miui_LANCELOT_V13.0.5.0.SJCCNXM_9a2b91926f_12.0.zip
               ls
       - name: Build twrp
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$SYM$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET$IMAGE -j60
              zip twrp.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/$TARGET$FORMAT

       - name: Save in artifact
         uses: actions/upload-artifact@v3
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/twrp.zip
            retention-days: 5
