name: Building Kernel New

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

      
                               
       - name: sync clang And Kernel
         run: |
            cd ~
            git clone --depth=1 https://github.com/Arafattex/oc_a13r.git -b a13r kernel
            cd kernel
            mkdir clang-13
            cd clang-13
            git clone https://github.com/vijaymalav564/vortex-clang.git -b master --depth=1 aaa
            
       - name: Build Kernel 
         run: |
            cd ~
            cd kernel
            chmod 0777 lancelot.sh
            ./shiva.sh
            

       - name: Kernel
         uses: actions/upload-artifact@v3
         with:
            name: kernels.zip
            path: /home/runner/kernel/AnyKernel3-master/Shas-Dream-*.zip
            retention-days: 5
