name: Building Kernel New

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.4

    steps:
       - name: Checkout
         uses: actions/checkout@master

      
                               
       - name: sync clang And Kernel
         run: |
            cd ~
            git clone --depth=1 https://github.com/Arafattex/shas-dream-oc-mt6768-a11 -b shas-noc kernel

            cd kernel
            #git clone https://github.com/rama982/AnyKernel3 --depth=1 AnyKerne3-master
            mkdir clang-13
            cd clang-13
            git clone https://github.com/vijaymalav564/vortex-clang.git -b master --depth=1 aaa
            
       - name: Build Kernel 
         run: |
            cd ~
            cd kernel
            chmod 0777 lancelot.sh
            chmod 0777 merlin.sh
            ./lancelot.sh
            

       - name: Kernel
         uses: actions/upload-artifact@v3
         with:
            name: kernel_lanc.zip
            path: /home/runner/kernel/AnyKernel3-master/*.zip
            #path: /home/runner/kernel/outM/arch/arm64/boot/Image.gz
            retention-days: 5
