name: Building Kernel New

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: sync clang And Kernel
         run: |
            cd ~
            git clone --depth=1 https://github.com/rama982/clang.git -b master toolchains/proton-clang
            git clone --depth=1 https://github.com/Arafattex/oc_a13r.git --b a13r kernel

       - name: Build Kernel 
         run: |
              cd ~
              cd kernel
              export PATH="$HOME/toolchains/proton-clang/bin:$PATH"
              mkdir out
              export ARCH=arm64
              export SUBARCH=arm64
              export DTC_EXT=dtc
              make O=out ARCH=arm64 lancelot_defconfig
              make -j"$PROCS" O=out \
                              ARCH=arm64 \
                              CC=clang \
                              CROSS_COMPILE=aarch64-linux-gnu- \
                              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                              LD=ld.lld \
                              NM=llvm-nm \
                              OBJCOPY=llvm-objcopy

       - name: Kernel
         uses: actions/upload-artifact@v3
         with:
            name: kernel.zip
            path: /home/runner/kernel/out/arch/arm64/boot/Image.gz-dtb
            retention-days: 5

       - name: Dtbo
         uses: actions/upload-artifact@v3
         with:
            name: dtbo.zip
            path: /home/runner/kernel/out/arch/arm64/boot/dtbo.img
            retention-days: 5
