name: kernel builder

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:

  KS_LINK: https://github.com/Arafattex/shas-dream-oc-mt6768-a11 -b shas-noc
  Device: lancelot
  Repo: shas-dream-oc-mt6768-a11

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             git clone $KS_LINK --depth=1    
             cd $Repo
             git clone https://github.com/kdrag0n/proton-clang.git clang-llvm --depth=1 
         
       - name: Build
         run: |
              cd /home/runner/work/Recovery_builder/Recovery_builder/work/$Repo
              mkdir outL
              export ARCH=arm64
              export SUBARCH=arm64
              export DTC_EXT=dtc
              make O=outL ARCH=arm64 lancelot_defconfig
              export PATH="/home/runner/work/Recovery_builder/Recovery_builder/work/$Repo/clang-llvm/bin:${PATH}"
              make -j50 O=outL \
                                    ARCH=arm64 \
                                    CC=clang \
                                    CROSS_COMPILE=aarch64-linux-gnu- \
                                    CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                                    LD=ld.lld \
                                    NM=llvm-nm \
                                    OBJCOPY=llvm-objcopy
              bp=${PWD}/outL
              ZIPNAME="$Device"
              cd ${PWD}/AnyKernel3-master
              cp $bp/arch/arm64/boot/Image.gz-dtb
              zip -r9 "$ZIPNAME".zip *
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: $ZIPNAME.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/$Repo/AnyKernel/$ZIPNAME.zip
            retention-days: 5
