name: "Mt6768 kernel"              # Description of the workflow.
on:
  push:
    branches: darky                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Mt6768 kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: Arafattex/AnyKernel3       # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: Arafattex/oc_a13r@a13r
      with:
        arch: arm64                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: lancelot_defconfig                    # Specify defconfig to use
        image: Image.gz-dtb
