name: Building My twrp recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/Arafattex/platform_manifest_twrp_aosp -b twrp-11
  DEVICE: lancelot
  DT_LINK: https://github.com/Arafattex/twrp_tree_mt6768 -b lancelot_a11t
  DT_PATH: device/xiaomi/lancelot
  TYPE: recoveryimage
  OT: omni_
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            df -BM
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            df -BM
           
            
            
       - name: Sync recovery source and device tree
         run: |
              repo init -u https://github.com/PixelExperience/manifest -b thirteen
              curl -o .repo/local_manifests/local_manifests.xml https://raw.githubusercontent.com/Arafattex/local_manifest/sex/local_manifest.xml --create-dirs
              repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags


       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TYPE -j20
              zip shrp.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/recovery.img
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: recovershiv12.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/work/shrp.zip
            retention-days: 5
