name: OFOX Build
on:
#  release:
#    types: [published]
#  push:
#   cd /home/runner/work/Recovery_builder/Recovery_builder/OrangeFox_sync/ofox/fox_11.0
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0
  DEVICE: lancelot
  DT_LINK: https://github.com/Arafattex/twrp_tree_mt6768 -b lancelot_a11_pb
  DT_PATH: device/xiaomi/lancelot
  TYPE: recoveryimage
  OT: omni_
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            df -BM
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove  aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "Ayush"
            git config --global user.email "ayush@disroot.org"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean
            sudo apt-get autoremove 
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl  bison aria2 coreutils
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            df -BM


       - name: sync ofox and build
         run: |
          mkdir ~/OrangeFox_sync
          cd ~/OrangeFox_sync
          git clone https://github.com/Arafattex/ofox.git
          ls
          cd ~/OrangeFox_sync/ofox/
          ./orangefox_sync.sh --branch 11.0 
          cd fox_11.0
          git clone $DT_LINK $DT_PATH --depth=1
         
       - name: Build
         run: |
          cd /home/runner/OrangeFox_sync/ofox/fox_11.0
          echo "::group::Run Envsetup.sh"
          . build/envsetup.sh
          echo "::endgroup::"
          echo "::group::Set
	  export TW_DEFAULT_LANGUAGE="en" EnvPath"
	
          exort ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          export TW_DEFAULT_LANGUAGE="en"
          export FOX_VERSION="Unofficial"
   	      
	  export TARGET_DEVICE_ALT="shiva"

	  export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system"
	  export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor"
	  export OF_QUICK_BACKUP_LIST="/boot;/data;"
	  export FOX_BUGGED_AOSP_ARB_WORKAROUND="1588606644"
          export FOX_RECOVERY_INSTALL_PARTITION="/dev/block/by-name/recovery"
          export OF_SCREEN_H=2340
	  export OF_STATUS_INDENT_LEFT="48"
	  export OF_STATUS_INDENT_RIGHT="48"
	  export OF_ALLOW_DISABLE_NAVBAR="0"
	  export OF_USE_MAGISKBOOT=1
	  export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
	  export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
	  export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
	  export OF_NO_MIUI_PATCH_WARNING=1
          export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1
	  export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
          export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
	  export OF_OTA_BACKUP_STOCK_BOOT_IMAGE=1
          export FOX_BUILD_TYPE="Unofficial"
	  export OF_MAINTAINER="@shas45558"
	  export FOX_VERSION="R11.1_2-@shas45558"
	  export FOX_ENABLE_APP_MANAGER=1
	  export FOX_USE_BASH_SHELL=1
	  export FOX_ASH_IS_BASH=1
	  export FOX_USE_NANO_EDITOR=1
	  export FOX_USE_TAR_BINARY=1
	  export FOX_USE_SED_BINARY=1
	  export FOX_USE_XZ_UTILS=1
	  export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
	xport OF_DONT_PATCH_ON_FRESH_INSTALLATION=1
	      export FOX_R11=1
	      export OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI=1
	      export OF_FLASHLIGHT_ENABLE=0
	      export FOX_DELETE_AROMAFM=1
	      export OF_PATCH_AVB20=1
	      export OF_FBE_METADATA_MOUNT_IGNORE="1"
	      export FOX_REPLACE_BUSYBOX_PS="0"
	      export OF_CHECK_OVERWRITE_ATTEMPTS=1
	      export OF_USE_SYSTEM_FINGERPRINT=1
	      export OF_NO_MIUI_PATCH_WARNING=1
	      export OF_USE_LOCKSCREEN_BUTTON=1
	      export FOX_ENABLE_APP_MANAGER=0
	      export FOX_VARIANT=MIUI
	      export FOX_DELETE_INITD_ADDON=1
	      export OF_SKIP_ORANGEFOX_PROCESS=1
	      export OF_RUN_POST_FORMAT_PROCESS=1
              echo "::endgroup::"
              echo "::group::Lunch 
              lunch $OT$DEVICE-eng
              echo "::endgroup::"
              echo "::group::Build
              mka $TYPE -j20
              zip ofox.zip /home/runner/OrangeFox_sync/ofox/fox_11.0/out/target/product/$DEVICE/recovery.img
              echo "::endgroup::"
             
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: recoverylanofox.zip
            path: /home/runner/OrangeFox_sync/ofox/fox_11.0/ofox.zip
            retention-days: 5
      
