name: OFOX Build
on:
  workflow_dispatch:
    inputs:
      crypto:
        description: "Whether to disable the encryption module, true or false"
        required: false
        default: "false"
      Enable_cache:
        description: "Enable cache, true or false"
        required: true
        default: "true"
      Delete_oldReleases:
        description: "whether to delete old postings, true or false"
        required: false
        default: "false"
env:
  Rec_name: Ofox
  Rec_ver: "11.0"
  Rec_url: https://gitlab.com/OrangeFox/sync.git -b master
  device: lancelot
  DT_url: https://github.com/Arafattex/twrp_tree_mt6768.git -b lancelot_a11
  DT_path: device/xiaomi/lancelot
  ProductFileHeader: omni
  target: recoveryimage
  WorkSpace: WorkSpace
  TZ: Asia/Calcutta
  Author: ${{github.actor}}
  Delete_old: false

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            df -BM
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove  aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "Ayush"
            git config --global user.email "ayush@disroot.org"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean
            sudo apt-get autoremove 
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl  bison aria2 coreutils
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            df -BM


       - name: sync ofox
         run: |
          mkdir ${{env.WorkSpace}}
          git clone ${{env.Rec_url}} --depth=1 --single-branch
          cd sync
          echo "::group::Orangefox_sync help"
          ./orangefox_sync.sh --help
          echo "::endgroup::"
          echo "::group::Run Orangefox_sync.sh"
          ./orangefox_sync.sh --branch ${{env.Rec_ver}} --path ${{github.workspace}}/${{env.WorkSpace}} --ssh 0
          echo "::endgroup::"
          echo "::group::sync Orangefox"
          cd ${{github.workspace}}/${{env.WorkSpace}}
          repo sync -j4 --force-sync
          rm -rf .repo
          echo "::endgroup::"

       - name: Sync device tree
         run: |
          cd ${{env.WorkSpace}}
          git clone ${{env.DT_url}} --depth=1 --single-branch ${{env.DT_path}}

       - name: Build ${{env.Rec_name}}
         run: |
          cd ${{env.WorkSpace}}
          pwd
          echo "::group::Run Envsetup.sh"
          source build/envsetup.sh
          echo "::endgroup::"
          echo "::group::Set EnvPath"
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          echo "::endgroup::"
          echo "::group::Lunch ${{env.ProductFileHeader}}_${{env.device}}-eng"
          lunch ${{env.ProductFileHeader}}_${{env.device}}-eng
          zip ofox.zip /home/runner/work/Recovery_builder/Recovery_builder/${{github.workspace}}/${{env.WorkSpace}}/out/target/product/lancelot/recovery.img
         shell: bash

       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: recoverylance.zip
            path: /home/runner/work/Recovery_builder/Recovery_builder/${{github.workspace}}/${{env.WorkSpace}}/ofox.zip
            retention-days: 5

      
