name: Building Pbrp recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/PitchBlackTWRP/manifest_pb.git -b android-10.0
  DEVICE: m10lte
  DT_LINK: https://github.com/AndVer0/android_device_samsung_m10lte_pbrp
  DT_PATH: device/samsung/m10lte
  TARGET: recoveryimage
  OT: omni_
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
              repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
              curl -o .repo/local_manifests/local_manifests.xml https://raw.githubusercontent.com/Arafattex/local_manifest/Lancelot_pixel/local_manifest.xml --create-dirs
              repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch $OT$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET -j110
              sudo apt install zip
              zip pbrp.zip /home/runner/work/Recovery_builder/Recovery_builder/work/out/target/product/$DEVICE/*.zip

       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: recovery.zip
            path: /home/runner/work/Recovery-builder/Recovery-builder/work/pbrp.zip
            retention-days: 5
