name: Recovery tester

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Adding and Sync source
         run: |
              repo init --depth=1 --no-repo-verify -u https://github.com/crdroidandroid/android -b 13.0 -g default,-mips,-darwin,-notdefault
              git clone https://github.com/Arafattex/local_manifest.git --depth 1 -b Lancelot_crdroida13r .repo/local_manifests
              repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
