name: Recovery tester

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Adding and Sync source
         run: |
              cd ~
              mkdir kernel
              cd kernel
              wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-13.0.0_r20/clang-r450784d.tar.gz
              tar -zxvf clang-r450784d.tar.gz
              ls
