name: Twrpdtgen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

      
                               
       - name: sync clang And Kernel
         run: |
            cd ~
            pip3 install twrpdtgen
            wget https://github.com/Arafattex/temp/blob/main/los_recovery.img?raw=true
            python3 -m twrpdtgen /home/runner/los_recovery.img?raw=true
            zip -r output.zip output
            ls


            

       - name: Kernel
         uses: actions/upload-artifact@v3
         with:
            name: twrp.zip
            path: /home/runner/output.zip
            retention-days: 5
